Lint/EndAlignment:
  Exclude:
    - 'lib/chest/cli.rb'

# Offense count: 3
Lint/Eval:
  Exclude:
    - 'spec/spec_helper.rb'

# Offense count: 4
Metrics/AbcSize:
  Max: 31

# Offense count: 1
# Configuration parameters: CountComments.
Metrics/ClassLength:
  Max: 115

# Offense count: 16
# Configuration parameters: AllowHeredoc, AllowURI, URISchemes.
# URISchemes: http, https
Metrics/LineLength:
  Max: 184

# Offense count: 6
# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 25

# Offense count: 2
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: nested, compact
Style/ClassAndModuleChildren:
  Exclude:
    - 'lib/chest/cli.rb'
    - 'lib/chest/registry.rb'

# Offense count: 5
Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'lib/chest/cli.rb'
    - 'lib/chest/config.rb'
    - 'lib/chest/helper.rb'
    - 'lib/chest/plugin_folder.rb'
    - 'lib/chest/registry.rb'

# Offense count: 2
# Configuration parameters: MinBodyLength.
Style/GuardClause:
  Exclude:
    - 'lib/chest/plugin_folder.rb'
    - 'lib/chest/registry.rb'

# Offense count: 1
Style/MethodMissing:
  Exclude:
    - 'lib/chest/config.rb'

# Offense count: 2
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles, AllowInnerSlashes.
# SupportedStyles: slashes, percent_r, mixed
Style/RegexpLiteral:
  Exclude:
    - 'lib/chest/helper.rb'
    - 'lib/chest/registry.rb'
